### ISSUE TITLE
concealed objects in auto-driving scenarios

### ISSUE THREAD

**Issue by WkangLiu** [DengPingFan/CSU#1]
Very nice job!
I am very interested in the concealed objects in auto-driving scenarios mentioned in the article.
Is there any specific work mentioned?

**Comment by DengPingFan** [comment]
Hi,

We have some on going projects now. It will be released several months
later.

Best,

Deng-Ping Fan

WkangLiu ***@***.***> 于2023年5月3日周三 10:18写道：

**Comment by WkangLiu** [comment]
Thank you!
