### ISSUE TITLE
Could provide the bbox annotation file for the CDS2K dataset?

### ISSUE THREAD

**Issue by ChialinSung** [DengPingFan/CSU#2]
I am doing hidden defect target detection, Could provide the annotation file of the bbox of the dataset? Also is it possible to provide a benchmark for target detection?
thanks，
Chialin

**Comment by DengPingFan** [comment]
Hi, 

You can generate via the object-level mask. We didn't provide the bbox of annotation currently. 

Best,

Deng-Ping
