### ISSUE TITLE
CDS2K download link expired

### ISSUE THREAD

**Issue by leimeng86** [DengPingFan/CSU#3]
Hi there,

The concealed defect segmentation dataset ([download, 159MB](https://anu365-my.sharepoint.com/:u:/g/personal/u7248002_anu_edu_au/EaInvU0siBNJvn6owmkbxbkBROwCGGt0ZUHmSj31XtaMPQ?e=wK6s9e)) link has expired.

Can you renew it?

Regards

**Comment by GewelsJI** [comment]
Hi, @leimeng86 

I have updated download link from OneDrive to googledrive: https://drive.google.com/file/d/1OGPR34qCNWHVYwyf9OY6IH-7WHzPkC7-/view
