### ISSUE TITLE
Some problem about the 'CDS2K' dataset

### ISSUE THREAD

**Issue by Delta0406** [DengPingFan/CSU#5]
May I ask why there is no data from the CrackForest dataset in the negative samples of the CDS2K dataset, while it is present in the positive samples? What is the rationale behind this decision?Additionally, could you provide information on how the experiments in the paper were conducted with regard to the partitioning of this dataset? Is it possible to upload a pre-divided dataset for reference?

**Comment by GewelsJI** [comment]
Thanks for your nice questions here.

A1. CrackForest only provides 118 positive samples with labels.
A2. We simply test the SOTA CSU methods on all positive samples of our CDS2K dataset.
A3. We do not exactly split the dataset into training and testing partitions, which leave a room for further explorations, like building a benchmark, or something else. 

Best,
Gepeng.

**Comment by GewelsJI** [comment]
This issue is temporarily closed. Reopen if needed.
